version: '2'
services:
  db:
    restart: always
    image: postgres:12
    volumes:
      - /home/apps/fider/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fider
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  app:
    restart: always
    image: getfider/fider:stable
    expose:
      - 3000
    environment:
      # Public Host Name
      HOST_DOMAIN: ${HOST_DOMAIN}

      # Connection string to the PostgreSQL database
      DATABASE_URL: postgres://fider:${POSTGRES_PASSWORD}@db:5432/fider?sslmode=disable

      # Generate a 512-bit secret here https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx
      JWT_SECRET: ${JWT_SECRET}
      OAUTH_GITHUB_CLIENTID: ${OAUTH_GITHUB_CLIENTID}
      OAUTH_GITHUB_SECRET: ${OAUTH_GITHUB_SECRET}

      # From which account e-mails will be sent
      EMAIL_NOREPLY: ${EMAIL_NOREPLY}

      ###
      # EMAIL
      # Either EMAIL_MAILGUN_* or EMAIL_SMTP_* is required
      ###

      # EMAIL_MAILGUN_API: key-yourkeygoeshere
      # EMAIL_MAILGUN_DOMAIN: yourdomain.com

      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      EMAIL_SMTP_USERNAME: ${EMAIL_SMTP_USERNAME}
      EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD}
      EMAIL_SMTP_ENABLE_STARTTLS: 'true'
